export const courses = [
  {
    id: "html",
    title: "HTML & CSS",
    level: "Débutant",
    description: "Maîtrisez les fondamentaux du web avec HTML5 et CSS3. Créez des pages web modernes et responsives.",
    duration: "4h",
    skills: ["HTML5", "CSS3", "Responsive Design", "Sémantique Web"],
    modules: 10,
    icon: "🌐",
    color: "primary",
  },
  {
    id: "python",
    title: "Python",
    level: "Intermédiaire",
    description: "Apprenez Python de A à Z. Automatisation, data science et développement backend.",
    duration: "6h",
    skills: ["Python 3", "Algorithmes", "POO", "Data Science"],
    modules: 10,
    icon: "🐍",
    color: "secondary",
  },
  {
    id: "react",
    title: "React.js",
    level: "Intermédiaire",
    description: "Construisez des interfaces modernes avec React. Components, hooks et state management.",
    duration: "5h",
    skills: ["React", "Hooks", "JSX", "State Management"],
    modules: 10,
    icon: "⚛️",
    color: "primary",
  },
  {
    id: "management",
    title: "Management",
    level: "Débutant",
    description: "Leadership et gestion d'équipe. Apprenez à diriger des projets et motiver vos équipes.",
    duration: "3h",
    skills: ["Leadership", "Communication", "Gestion de projet", "Agilité"],
    modules: 10,
    icon: "📊",
    color: "secondary",
  },
  {
    id: "javascript",
    title: "JavaScript Avancé",
    level: "Avancé",
    description: "Plongez dans les concepts avancés de JavaScript : closures, prototypes, async/await.",
    duration: "7h",
    skills: ["ES6+", "Async", "Design Patterns", "Performance"],
    modules: 10,
    icon: "⚡",
    color: "primary",
  },
  {
    id: "devops",
    title: "DevOps & CI/CD",
    level: "Avancé",
    description: "Automatisez le déploiement et la livraison continue. Docker, GitHub Actions et plus.",
    duration: "5h",
    skills: ["Docker", "CI/CD", "Linux", "Cloud"],
    modules: 10,
    icon: "🚀",
    color: "secondary",
  },
];

export const leaderboard = [
  { rank: 1, name: "Kofi Adjovi", points: 4850, badges: 12, avatar: "KA", courses: 8 },
  { rank: 2, name: "Amina Bello", points: 4200, badges: 10, avatar: "AB", courses: 7 },
  { rank: 3, name: "Sékou Dossou", points: 3900, badges: 9, avatar: "SD", courses: 6 },
  { rank: 4, name: "Fatimatou Yao", points: 3600, badges: 8, avatar: "FY", courses: 6 },
  { rank: 5, name: "Hervé Ganvo", points: 3100, badges: 7, avatar: "HG", courses: 5 },
  { rank: 6, name: "Rachida Akpo", points: 2800, badges: 6, avatar: "RA", courses: 5 },
  { rank: 7, name: "Landry Hounsa", points: 2500, badges: 5, avatar: "LH", courses: 4 },
  { rank: 8, name: "Estelle Agbo", points: 2200, badges: 5, avatar: "EA", courses: 4 },
];

export const mockModules = [
  { id: 1, title: "Introduction et fondamentaux", completed: true },
  { id: 2, title: "Structure et syntaxe de base", completed: true },
  { id: 3, title: "Variables et types de données", completed: true },
  { id: 4, title: "Structures de contrôle", completed: false },
  { id: 5, title: "Fonctions et modularité", completed: false },
  { id: 6, title: "Manipulation de données", completed: false },
  { id: 7, title: "Concepts avancés", completed: false },
  { id: 8, title: "Projet pratique I", completed: false },
  { id: 9, title: "Projet pratique II", completed: false },
  { id: 10, title: "Révision et certification", completed: false },
];
